#!/bin/sh

PROFILE_NAME="arch-laptop"
PKG_INSTALL_FUNC="yay -Syu --noconfirm"
PKG_UNINSTALL_FUNC="yay -Rsn --noconfirm"


### Bash
_register_module "bash"
bash_pkgs="bash bash-completion tree unzip curl ripgrep fd fzf bat"

install_bash() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${bash_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${bash_pkgs}
    fi
}

deploy_bash() {
    if [ "$1" = "deploy" ]; then
        ln -sfn "${SRC_DIR}/bash/bashrc" "${DEST_DIR}/.bashrc"
        ln -sfn "${SRC_DIR}/bash/profile" "${DEST_DIR}/.bash_profile"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.bashrc"
        _rm "${DEST_DIR}/.bash_profile"
    fi
}


### Bin
_register_module "bin"

deploy_bin() {
    if [ "$1" = "deploy" ]; then
        chmod u+x ${SRC_DIR}/bin/*
    elif [ "$1" = "remove" ]; then
        chmod u-x ${SRC_DIR}/bin/*
    fi
}


### Emacs
_register_module "emacs"
emacs_pkgs="emacs-nox hunspell-fr hunspell-de hunspell-en_us hunspell-en_gb words clang pyright bash-language-server tree-sitter-c tree-sitter-python tree-sitter-bash"

install_emacs() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${emacs_pkgs}
        _log_msg "[emacs] You may want to install your Emacs flavor manually"
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${emacs_pkgs}
        _log_msg "[emacs] You may want to uninstall your Emacs flavor manually"
    fi
}

deploy_emacs() {
    if [ "$1" = "deploy" ]; then
        # A leftover ~/.emacs.d (older deploys) would shadow ~/.config/emacs
        [ -L "${DEST_DIR}/.emacs.d" ] && _rm "${DEST_DIR}/.emacs.d"
        mkdir -p "${DEST_DIR}/.config" && ln -sfn "${SRC_DIR}/emacs" "${DEST_DIR}/.config/emacs"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.config/emacs"
    fi
}


### Git
_register_module "git"
git_pkgs="git"

install_git() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${git_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${git_pkgs}
    fi
}

deploy_git() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.config/git"
        ln -sfn "${SRC_DIR}/git/config" "${DEST_DIR}/.config/git/config"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.config/git"
    fi
}


### GPG
_register_module "gnupg"
gnupg_pkgs="gnupg"

install_gnupg() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${gnupg_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${gnupg_pkgs}
    fi
}

deploy_gnupg() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.gnupg"
        ln -sfn "${SRC_DIR}/gnupg/gpg.conf" "${DEST_DIR}/.gnupg/gpg.conf"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.gnupg/gpg.conf"
    fi
}


### i3wm
_register_module "i3"
i3wm_pkgs="i3-wm i3status i3lock dmenu imagemagick"

install_i3() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${i3wm_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${i3wm_pkgs}
    fi
}

deploy_i3() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.config/i3/config"
        ln -sfn "${SRC_DIR}/i3/i3.conf" "${DEST_DIR}/.config/i3/config/i3.conf"
        ln -sfn "${SRC_DIR}/i3/statusbar" "${DEST_DIR}/.config/i3/statusbar"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.config/i3"
    fi
}


### Irssi
_register_module "irssi"
irssi_pkgs="irssi"

install_irssi() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${irssi_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${irssi_pkgs}
    fi
}

deploy_irssi() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.irssi"
        ln -sfn "${SRC_DIR}/irssi/config" "${DEST_DIR}/.irssi/config"
        ln -sfn "${SRC_DIR}/irssi/default.theme" "${DEST_DIR}/.irssi/default.theme"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.irssi"
    fi
}


### Newsboat
_register_module "newsboat"
newsboat_pkgs="newsboat"

install_newsboat() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${newsboat_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${newsboat_pkgs}
    fi
}

deploy_newsboat() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.config/newsboat"
        ln -sfn "${SRC_DIR}/newsboat/config" "${DEST_DIR}/.config/newsboat/config"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.config/newsboat"
    fi
}


### Ranger
_register_module "ranger"
ranger_pkgs="ranger"

install_ranger() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${ranger_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${ranger_pkgs}
    fi
}

deploy_ranger() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.config/ranger"
        ln -sfn "${SRC_DIR}/ranger/rc.conf" "${DEST_DIR}/.config/ranger/rc.conf"
        ln -sfn "${SRC_DIR}/ranger/rifle.conf" "${DEST_DIR}/.config/ranger/rifle.conf"
        ln -sfn "${SRC_DIR}/ranger/scope.sh" "${DEST_DIR}/.config/ranger/scope.sh"
        ln -sfn "${SRC_DIR}/ranger/commands.py" "${DEST_DIR}/.config/ranger/commands.py"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.config/ranger"
    fi
}


### Tmux
_register_module "tmux"
tmux_pkgs="tmux"

install_tmux() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${tmux_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${tmux_pkgs}
    fi
}

deploy_tmux() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.config/tmux"
        ln -sfn "${SRC_DIR}/tmux/tmux.conf" "${DEST_DIR}/.config/tmux/tmux.conf"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.config/tmux"
    fi
}


### XORG
_register_module "xorg"
xorg_pkgs="xorg xorg-xinit xorg-xrdb rxvt-unicode urxvt-perls urxvt-resize-font-git xclip feh unclutter scrot htop ttf-inconsolata xf86-video-intel ttf-dejavu alsa-utils sxiv xorg-xbacklight autocutsel xss-lock clipmenu wl-clipboard"

install_xorg() {
    if [ "$1" = "install" ]; then
        _add_to_pkgs ${xorg_pkgs}
    elif [ "$1" = "uninstall" ]; then
        _add_to_pkgs ${xorg_pkgs}
    fi
}

deploy_xorg() {
    if [ "$1" = "deploy" ]; then
        mkdir -p "${DEST_DIR}/.config/xorg"
        mkdir -p "${DEST_DIR}/images/shots"
        ln -sfn "${SRC_DIR}/xorg/xinitrc" "${DEST_DIR}/.xinitrc"
        ln -sfn "${SRC_DIR}/xorg/Xresources" "${DEST_DIR}/.config/xorg/Xresources"
        ln -sfn "${SRC_DIR}/xorg/Xlight_theme" "${DEST_DIR}/.config/xorg/Xlight_theme"
        ln -sfn "${SRC_DIR}/xorg/Xdark_theme" "${DEST_DIR}/.config/xorg/Xdark_theme"
        ln -sfn "${SRC_DIR}/xorg/typematrix.xkb" "${DEST_DIR}/.config/xorg/typematrix.xkb"
        ln -sfn "${SRC_DIR}/xorg/wallpapers/" "${DEST_DIR}/images/wallpapers"
    elif [ "$1" = "remove" ]; then
        _rm "${DEST_DIR}/.xinitrc"
        _rm "${DEST_DIR}/.config/xorg"
        _rm "${DEST_DIR}/images/wallpapers"
    fi
}
