#!/bin/sh

# Environment variables and global options
set -o emacs
shopt -s checkwinsize

TERM=xterm-256color

LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8

HISTFILE="$HOME/.sh_history"
HISTSIZE=10000
HISTFILESIZE=10000
HISTCONTROL=ignoredups:ignorespace

# Add $1 to $PATH if not already present
pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}


# Add custom, rust and go binaries to $PATH
[ -d "${HOME}/.dotfiles/bin" ] && pathadd "${HOME}/.dotfiles/bin"
[ -d "${HOME}/.cargo/bin" ] && pathadd "${HOME}/.cargo/bin"
[ -d "${HOME}/go/bin" ] && pathadd "${HOME}/go/bin"


# Set default editor
if [ -x "$(command -v emacsclient)" ] ; then
    EDITOR='emacsclient -t -a ""'
    ALTERNATE_EDITOR='emacsclient -t -a ""'
    VISUAL='emacsclient -t -a ""'

elif [ -x "$(command -v emacs)" ] ; then
    EDITOR=emacs
    ALTERNATE_EDITOR=emacs
    VISUAL=emacs

elif [ -x "$(command -v nano)" ] ; then
    EDITOR=nano
    ALTERNATE_EDITOR=nano
    VISUAL=nano

else # God have mercy
    EDITOR=vi
    ALTERNATE_EDITOR=vi
    VISUAL=vi
fi

alias e=${EDITOR}
alias emc=${EDITOR}

# Nicer prompt
if [ $(id -u) == "0" ]; then
    PS1='\[\e[0;31m\]\u\[\e[m\]@\h:\[\e[0;35m\]\w\[\e[m\]\[\e[0;31m\]\n$\[\e[m\] '
else
    PS1='\[\e[0;32m\]\u\[\e[m\]@\h:\[\e[0;35m\]\w\[\e[m\]\[\e[0;32m\]\n$\[\e[m\] '
fi

# OpenBSD specific
if [ "$(uname)" = "OpenBSD" ]; then
    [ -x "$(command -v doas)" ] && alias sudo='doas'
    alias poweroff='sudo shudown -p now'
    bind -m ^L='clear'^J
fi

# Specific tools
[ -x "$(command -v curl)" ]     && alias weather='curl -s wttr.in/?nFQ '
[ -x "$(command -v less)" ]     && alias more='less '
[ -x "$(command -v newsboat)" ] && alias newsboat='newsboat -u ${HOME}/.my_private/newsboat/urls '
[ -x "$(command -v sxiv)" ]     && alias sxiv='sxiv -a '
[ -x "$(command -v tree)" ]     && alias tree='tree -F '
[ -x "$(command -v urxvtc)" ]   && alias mm='urxvtc -cd "$PWD" & '

# Tmux utility aliases
if [ -x "$(command -v tmux)" ]; then
    alias t='tmux'
    alias ta='tmux attach -t'
    alias tls='tmux ls'
    alias tks='tmux kill-session -t'
fi

# Search through files with ripgrep
if [ -x "$(command -v rg)" ]; then
    alias rgi='rg -i'
    alias rgia='rg -i -a '
    alias rgl='rg -l'
    alias rgla='rg -l -a'
    alias rgil='rg -i -l'
    alias rgila='rg -i -l -a'
fi

# Ranger / Rifle
if [ -x "$(command -v ranger)" ]; then
    ranger() {
        if [ -n "$RANGER_LEVEL" ]; then
            echo "Already inside ranger"
            return 1
        fi
        command ranger "$@"
    }

    alias o='rifle '
    alias r='ranger '
fi

# gf (https://github.com/tomnomnom/gf)
if [ -x "$(command -v gf)" ]; then
    complete -W "\$(gf -list)" gf
fi

# fzf (requires bat, rifle, fd and rg)
if [ -x "$(command -v fzf)" ]; then

    eval "$(fzf --bash)"

    # Select items from stdin with fzf. C-o will open files with emacs and Enter
    # with rifle. M-o will print selection to stdout, M-i will store it in the
    # clipboard. M-d and M-a (de)select everything and C-/ toggles the preview
    # windows. C-j and C-k scroll the preview window.
    fo() {
        IFS=$'\n' fzf --multi --ansi \
           --scheme=path \
           --reverse --border --height 80% \
           --bind 'enter:execute:rifle {+}' \
           --bind 'ctrl-o:execute:$EDITOR {+}' \
           --bind "alt-o:become(echo {+} | tr ' ' '\n')" \
           --bind 'alt-i:execute-silent(for item in {+}; do echo $item; done | xsel -i)' \
           --bind 'alt-a:select-all,alt-d:deselect-all,ctrl-/:toggle-preview' \
           --bind 'ctrl-j:preview-down,ctrl-k:preview-up' \
           --preview 'preview-file.sh {}'
    }

    # List files in directory $1 with 'fd' options $@ and send them to 'fo'
    ff() {
        cd ${1:-.}
        shift
        fd "$@" 2>/dev/null | fo
        cd - 1>/dev/null
    }

    ## Same as 'ff' but search all hidden / ignored files
    ffa() {
        cd ${1:-.}
        shift
        fd -u "$@" 2>/dev/null | fo
        cd - 1>/dev/null
    }

    # Search with 'rg' for files in $1 matching given query. Open them in emacs
    # with C-o and with rifle with Enter. C-f opens a temporary files with all
    # the matches. M-o prints them to stdout, M-i copies them to the clipboard,
    # M-h copies only the filenames. C-j and C-k scroll the preview windows. M-d
    # and M-a (de)select everything and C-/ toggles the preview window.
    fr() {
        RELOAD='reload:rg --line-number --color=always --smart-case {q} || :'
        OPENER_EMACS='if [[ $FZF_SELECT_COUNT -eq 0 ]]; then
            $EDITOR +{2} {1}
          else
            for item in {+}; do echo $item | cut -d ":" -f1; done | xargs $EDITOR
          fi'
        OPENER_RIFLE='for item in {+}; do echo $item | cut -d ":" -f1; done | xargs rifle'

        cd ${1:-.}
        shift
        fzf --ansi --multi \
            --reverse --height 80% --border \
            --bind "start:$RELOAD" --bind "change:$RELOAD" \
            --bind "enter:execute:$OPENER_RIFLE" \
            --bind "ctrl-o:execute:$OPENER_EMACS" \
            --bind "ctrl-f:execute:$EDITOR {+f}" \
            --bind 'alt-o:become(for item in {+}; do echo $item; done)' \
            --bind 'alt-a:select-all,alt-d:deselect-all,ctrl-/:toggle-preview' \
            --bind "alt-i:execute-silent(echo {+} | tr ' ' '\n' | xsel -i)" \
            --bind 'alt-h:execute-silent(for item in {+}; do echo $item | cut -d":" -f1; done | sort -u | xsel -i)' \
            --bind 'ctrl-j:preview-down,ctrl-k:preview-up' \
            --delimiter : \
            --preview 'bat --style=header --color=always -H {2} {1}' \
            --preview-window 'down'

        cd - 1>/dev/null
    }

    # Same as 'fr' but with hidden / ignored files
    fra() {
        RELOAD='reload:rg -uu --line-number --color=always --smart-case {q} || :'
        OPENER='if [[ $FZF_SELECT_COUNT -eq 0 ]]; then
            emacsclient -t +{2} {1}
          else
            emacsclient -t {+f}
          fi'

        cd ${1:-.}
        shift
                fzf --ansi --multi \
            --reverse --height 80% --border \
            --bind "start:$RELOAD" --bind "change:$RELOAD" \
            --bind "enter:execute:$OPENER_RIFLE" \
            --bind "ctrl-o:execute:$OPENER_EMACS" \
            --bind "ctrl-f:execute:$EDITOR {+f}" \
            --bind 'alt-o:become(for item in {+}; do echo $item; done)' \
            --bind 'alt-a:select-all,alt-d:deselect-all,ctrl-/:toggle-preview' \
            --bind "alt-i:execute-silent(echo {+} | tr ' ' '\n' | xsel -i)" \
            --bind 'alt-h:execute-silent(for item in {+}; do echo $item | cut -d":" -f1; done | sort -u | xsel -i)' \
            --bind 'ctrl-j:preview-down,ctrl-k:preview-up' \
            --delimiter : \
            --preview 'bat --style=header --color=always -H {2} {1}' \
            --preview-window 'down'

        cd - 1>/dev/null
    }
fi

# Start irssi with personal config and private settings
if [ -x "$(command -v irssi)" ]; then
    alias irssi-libera='irssi --config=<((cat ${HOME}/.irssi/config 2>/dev/null && cat ${HOME}/.my_private/irssi/libera 2>/dev/null))'
    alias irssi-hackerzvoice='irssi --config=<((cat ${HOME}/.irssi/config 2>/dev/null && cat ${HOME}/.my_private/irssi/hackerzvoice 2>/dev/null))'
fi

# Reset setxkbmap to fr+bepo
alias bepomap='setxkbmap fr,fr oss,bepo grp:alt_caps_toggle,grp_led:scroll'

# Aliases for standard utils
alias dm='dmesg | tail'
alias h='fc -l'
alias hh='fc -l -1 -300|grep'
alias hhh='fc -l -1 -${HISTSIZE}|grep'
alias hi='ping -c 3 example.com'
alias j='jobs'
alias ls='ls -F --color=auto'
alias l='ls -F --color=auto'
alias la='ls -aF --color=auto'
alias ll='ls -lisahF --group-directories-first'
alias llm='ls -lisahF --group-directories-first | more'
alias madiff='diff -ENwbur'
alias mkdir='mkdir -p'
alias p='ps -l'
alias pa='ps -aux'
alias pz='ps -aux|grep -v grep |grep'
alias please='sudo $(fc -ln -1)'
alias plz='please'
alias q='exit'
alias reset-dhcpcd='sudo dhcpcd && sleep 3 && sudo resolvconf -u '
alias remove-empty-files='find . -size 0 -print0 | xargs -0 rm -- '
alias remove-empty-directories='find . -type d -empty -delete '
alias x='cd $HOME && startx'

# Utility functions
mkdircd() {
    mkdir -p "$1"
    cd "$1" || return
}

cdls() {
    cd "$1" || return
    ls -lisa "$1"
}

# Add a new cronjob formatted string to crontab
add-cronjob() {
    [ -n "$1" ] && crontab -l 2> /dev/null |
            { cat; echo "$1"; } | sort | uniq | crontab -
}

# Extract various types of archives according to filename extension
extract-archive() {
    if [ -f "$1" ] ; then
        case "$1" in
            *.7z)        7z x "$1"      ;;
            *.Z)         uncompress "$1";;
            *.tar)       tar xfv "$1" ;;
            *.tar.bz2)   tar xjfv "$1" ;;
            *.tar.gz)    tar xzfv "$1" ;;
            *.tbz2)      tar xjfv "$1" ;;
            *.tgz)       tar xzfv "$1" ;;
            *.bz2)       bunzip2 "$1" ;;
            *.gz)        gunzip "$1" ;;
            *.rar)       unrar x "$1" ;;
            *.xz)        unxz "$1" ;;
            *.zip)       unzip "$1" ;;
            *)           echo "Could not match extension of $1" ;;
        esac
    fi
}

# Generate an alphanumerical password of length $1 with some special chars
passwd-gen() {
    tr -dc '[:alnum:]+,;/-=:&$(){}[]' < /dev/urandom \
        | fold -w "${1:-16}" | head -n 1
}

# Decode b64 input from $1
b64d() { echo -n "$1" | base64 -i -d ;}

# Print timestamps
ts-day() { date "+%Y-%m-%d" ; }
ts-time() { date "+%Y-%m-%d_%H-%M-%S" ; }

# Simply source existing file
source-if-exists() {
    [ -f "$1" ] && . "$1"
}

# create output image $1 from input $1 and writes text $3 in red across it
print-on-image() {
    input="$1"
    output="$2"
    text="$3"
    color="255,0,0,0.25" # red
    convert -density 150 -fill "rgba(${color})" \
            -gravity Center -pointsize 80 \
            -draw "rotate -45 text 0,0 \"${text}\"" \
            "${input}" "${output}"
}

# Switch Xorg theme
xorg-switch-theme() {
    theme="${HOME}/.config/xorg/X${1}_theme"
    [ -f "${theme}" ] && xrdb -override -I"$(dirname ${theme})" "${theme}"
}

# Convert html to pdf with chromium's headless browser
html-to-pdf() {
    chromium --headless --print-to-pdf="$2" --print-to-pdf-no-header "$1"
}

# Get rid of non-ascii chars in a file ($1)
remove-non-ascii() {
    local tmp_dir="$(mktemp -d)"
    cat "$1" | tr -d '\200-\377' > "${tmp_dir}/$1"
    cp "${tmp_dir}/$1" "$1"
    rm -rf "${tmp_dir}"
}

# Get rid of BOM in file ($1)
remove-bom() {
    sed -i '1s/^\xEF\xBB\xBF//' "$1"
}

# My docker stuff
[ -f "${HOME}/tools/dockers/aliases.sh" ] && source "${HOME}/tools/dockers/aliases.sh"

# Finally export all the thingz! (just in case)
export PS1
export PATH HOME TERM
export LANG LC_ALL
export ALTERNATE_EDITOR EDITOR VISUAL
export HISTFILE HISTSIZE HISTCONTROL
